# Generated by Django 5.0 on 2025-07-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalinfo',
            old_name='facbook_url',
            new_name='facebook_url',
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='company_name',
            field=models.CharField(default=' Company ', max_length=300),
        ),
    ]
