# Generated by Django 5.0 on 2025-07-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='testinomial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.CharField(blank=True, max_length=255, null=True)),
                ('rating_count', models.IntegerField()),
                ('user_name', models.CharField(max_length=100)),
                ('user_job_title', models.CharField(max_length=100)),
                ('review', models.TextField()),
            ],
        ),
    ]
