# Generated by Django 5.0 on 2025-07-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_testinomial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testinomial',
            name='rating_count',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')]),
        ),
    ]
